### PR TITLE
Add Crayon Syntax Highlighter support to the 'remote-markdown' shortcode

### PR DESCRIPTION
**Pull request by guylabs**
Hi Andrés,

as I am using the [Crayon Syntax Highlighter](https://wordpress.org/plugins/crayon-syntax-highlighter) plugin in my Wordpress instance, I thought I could add the support for it to your wp-remote-markdown plugin.

Could you please have a look at it and maybe merge it to the master branch and release a new version? (If you like this small feature).

Regards,

Guy

### CODE REVIEW

**Comment by andrezrv** [comment]
I don't know how I ended up skipping this pull request :/

It seems like a great idea. I'll try it locally before merging it :)

**Comment by guylabs** [comment]
ok thanks :). If you have questions just ask me.

**Comment by guylabs** [comment]
And any news about the local test ? :)

**Comment by andrezrv** [comment]
I just added this to the main repo. Sorry for the huge delay, I haven't been really using this plugin lately and couldn't find a time to test the changes.

I enforced `$atts['crayon']` to only accept `1` and `true` in order to evaluate to true. Hope that doesn't break anything on your side.

**Comment by guylabs** [comment]
Hi Andrés,

thanks a lot for accepting the pull request :). Yes that also works with `1` or `true`.

Thanks and regards,

Guy

**Pull request merged**
